name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request_target:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ matrix.node-version }}
    - name: Init docker with docker-compose
      run: docker-compose --profile dev -f docker-compose.yml up -d
    - name: Docker status
      run: docker ps -a
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Unit Test
      run: yarn test unit:coverage
    - name: Unit Test Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/unit/lcov.info
        flag-name: Unit(Node-${{ matrix.node-version }})
        parallel: true
    - name: Integration Test
      run: yarn test integrate:coverage
    - name: Integration Test Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/integrate/lcov.info
        flag-name: Integration(Node-${{ matrix.node-version }})
        parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
